"""E53 — per-room accuracy, reported as a distribution and never as one number.

The first instinct is to print

    total vector area   412.6 m2
    total site area     409.1 m2
    difference          0.9%

and it is worthless. A room measured 2 m2 too big and a room measured 2 m2 too
small cancel exactly, and the project total says the engine is accurate when
two rooms are wrong. A total is a check that ERRORS DID NOT ACCUMULATE; it is
not evidence that any individual room is right.

So this module reports:

    every room, with its own absolute difference and percentage
    the median absolute percentage
    the 90th percentile absolute percentage
    the worst room, by name

and only then the total, labelled as the secondary diagnostic it is.

NO ACCEPTANCE THRESHOLD IS DEFINED HERE. One project is not a population, and
a threshold set from 23010's first real run would be a number chosen to pass.
First measure the distribution; decide what is acceptable afterwards, with
evidence.

THE REFERENCE ANSWERS ARE NOT INPUTS. Vector faces are generated by the wall
graph before this module is called, and nothing here feeds back. A comparison
that could adjust the thing it compares is not a measurement.
"""

from __future__ import annotations

from dataclasses import dataclass

# What a comparison was made against. Each is a different kind of truth and
# they do not substitute for each other.
SOURCE_RASTER = "RASTER_SEGMENTATION"
SOURCE_PRINTED = "PRINTED_DESIGN_DIMENSION"
SOURCE_SITE = "SITE_MEASURED_QIYAL"

COMPARISON_SOURCES = (SOURCE_RASTER, SOURCE_PRINTED, SOURCE_SITE)

NOT_AVAILABLE = "NOT_AVAILABLE"

# The two bases this comparison keeps running into. A planar face is measured
# on wall centrelines because that is where the graph's edges are; a raster
# region is the clear internal opening.
WALL_CENTRELINE = "WALL_CENTRELINE"
CLEAR_INTERNAL = "CLEAR_INTERNAL_FINISH_FACE"

# How a centreline area was brought onto the clear-internal basis.
#
# RETIRED AS A MEASUREMENT BASIS. It is exact only for a single rectangle of
# uniform thickness: it has NO CORNER TERM, and inside and outside corners
# contribute with opposite sign, so on the L-shaped fixture it is out by
# exactly 0.04 m2 — five outside corners at +0.01 and one inside corner at
# -0.01. Mixed 100/150/200 mm walls break it again, because there is no single
# thickness to halve. Holes, shafts, T-junctions and bands with unequal face
# extents break it further.
#
# It survives ONLY as a diagnostic to compare against engine.clear_internal,
# which measures the polygon instead of adjusting a number.
ADJ_HALF_THICKNESS = "MINUS_PERIMETER_X_MEAN_HALF_WALL_THICKNESS"
DIAGNOSTIC_APPROXIMATION = "DIAGNOSTIC_APPROXIMATE_BASIS_CONVERSION"
MEASURED_POLYGON = "MEASURED_FROM_CLEAR_INTERNAL_POLYGON"

CONVERSION_KINDS = (DIAGNOSTIC_APPROXIMATION, MEASURED_POLYGON)


class AccuracyError(RuntimeError):
    """A comparison was asked for between two things that are not comparable."""


@dataclass(frozen=True)
class RoomAccuracy:
    """One room, one vector face, and every reference that exists for it."""

    space_id: str
    space_face_id: str
    measurement_basis: str
    vector_area_m2: float | None = None
    vector_perimeter_m: float | None = None
    raster_area_m2: float | None = None
    raster_perimeter_m: float | None = None
    printed_area_m2: float | None = None
    site_area_m2: float | None = None
    # NEVER COMPARE UNLIKE BASES. A planar face walks WALL CENTRELINES; a
    # raster region is the CLEAR INTERNAL opening between finished faces. They
    # differ by roughly half a wall thickness all the way round, and on a 5.5 m
    # bedroom that is about 10% of the area — which would be read as 10% error
    # by anyone who did not know the bases were different.
    vector_basis: str = WALL_CENTRELINE
    reference_basis: str = CLEAR_INTERNAL
    vector_area_basis_adjusted_m2: float | None = None
    basis_adjustment_m2: float | None = None
    basis_adjustment_method: str = ""
    # Which kind of number `comparable_vector_area_m2` is. A scalar conversion
    # is NOT per-room accuracy and must never be quoted as one.
    conversion_kind: str = DIAGNOSTIC_APPROXIMATION
    # Set when a real clear-internal polygon exists for this room.
    clear_internal_area_m2: float | None = None
    clear_internal_perimeter_m: float | None = None
    shape: dict | None = None
    why: str = ""

    @property
    def comparable_vector_area_m2(self) -> float | None:
        """The vector area on the REFERENCE's basis, when that is possible.

        Falls back to the raw centreline area, and `bases_match` says which
        happened, so a percentage is never read as accuracy when it is really
        a basis difference.
        """
        if self.clear_internal_area_m2 is not None:
            return self.clear_internal_area_m2
        if self.vector_basis == self.reference_basis:
            return self.vector_area_m2
        return (self.vector_area_basis_adjusted_m2
                if self.vector_area_basis_adjusted_m2 is not None
                else self.vector_area_m2)

    @property
    def bases_match(self) -> bool:
        return (self.clear_internal_area_m2 is not None
                or self.vector_basis == self.reference_basis
                or self.vector_area_basis_adjusted_m2 is not None)

    @property
    def is_measured(self) -> bool:
        """Is the comparable area MEASURED, or converted with a scalar?

        Only a measured one may be called per-room accuracy. §16.
        """
        return self.clear_internal_area_m2 is not None

    def _diff(self, other: float | None) -> tuple[float | None, float | None]:
        v = self.comparable_vector_area_m2
        if v is None or other is None or other == 0:
            return None, None
        d = v - other
        return abs(d), abs(d) / other * 100

    @property
    def vs_raster(self) -> tuple[float | None, float | None]:
        return self._diff(self.raster_area_m2)

    @property
    def vs_printed(self) -> tuple[float | None, float | None]:
        return self._diff(self.printed_area_m2)

    @property
    def vs_site(self) -> tuple[float | None, float | None]:
        return self._diff(self.site_area_m2)

    @property
    def best_reference(self) -> str:
        """The strongest reference actually present, by source hierarchy."""
        if self.site_area_m2 is not None:
            return SOURCE_SITE
        if self.printed_area_m2 is not None:
            return SOURCE_PRINTED
        if self.raster_area_m2 is not None:
            return SOURCE_RASTER
        return NOT_AVAILABLE

    @property
    def headline_abs_pct(self) -> float | None:
        """The percentage against the strongest reference present."""
        return {SOURCE_SITE: self.vs_site, SOURCE_PRINTED: self.vs_printed,
                SOURCE_RASTER: self.vs_raster}.get(
                    self.best_reference, (None, None))[1]

    def record(self) -> dict:
        ra, rp = self.vs_raster
        pa, pp = self.vs_printed
        sa, sp = self.vs_site
        return {
            "space_id": self.space_id, "space_face_id": self.space_face_id,
            "measurement_basis": self.measurement_basis,
            "vector_area_m2": _r(self.vector_area_m2),
            "vector_perimeter_m": _r(self.vector_perimeter_m),
            "vector_basis": self.vector_basis,
            "reference_basis": self.reference_basis,
            "bases_match": self.bases_match,
            "vector_area_basis_adjusted_m2": _r(
                self.vector_area_basis_adjusted_m2),
            "basis_adjustment_m2": _r(self.basis_adjustment_m2),
            "basis_adjustment_method": self.basis_adjustment_method,
            "conversion_kind": (MEASURED_POLYGON if self.is_measured
                                else DIAGNOSTIC_APPROXIMATION),
            "is_measured_not_converted": self.is_measured,
            "clear_internal_area_m2": _r(self.clear_internal_area_m2),
            "clear_internal_perimeter_m": _r(self.clear_internal_perimeter_m),
            "shape": self.shape,
            "comparable_vector_area_m2": _r(self.comparable_vector_area_m2),
            "raster_area_m2": _r(self.raster_area_m2),
            "raster_perimeter_m": _r(self.raster_perimeter_m),
            "printed_area_m2": _r(self.printed_area_m2),
            "site_area_m2": _r(self.site_area_m2),
            "abs_diff_vs_raster_m2": _r(ra), "pct_vs_raster": _r(rp),
            "abs_diff_vs_printed_m2": _r(pa), "pct_vs_printed": _r(pp),
            "abs_diff_vs_site_m2": _r(sa), "pct_vs_site": _r(sp),
            "best_reference": self.best_reference,
            "headline_abs_pct": _r(self.headline_abs_pct),
            "why": self.why}


def _r(v, n: int = 3):
    return None if v is None else round(v, n)


def _percentile(values, q: float) -> float | None:
    """Nearest-rank percentile. Small samples, so no interpolation is honest."""
    if not values:
        return None
    xs = sorted(values)
    i = min(len(xs) - 1, max(0, int(round(q / 100 * len(xs) + 0.5)) - 1))
    return xs[i]


def distribution(rooms) -> dict:
    """The shape of the error across rooms — never one project percentage.

    The total appears last and says what it is: a check that errors did not
    accumulate, not a measure of per-room accuracy.
    """
    scored = [r for r in rooms if r.headline_abs_pct is not None]
    pcts = [r.headline_abs_pct for r in scored]
    worst = max(scored, key=lambda r: r.headline_abs_pct, default=None)
    vec = sum(r.comparable_vector_area_m2 or 0.0 for r in scored)
    ref = 0.0
    for r in scored:
        ref += {SOURCE_SITE: r.site_area_m2, SOURCE_PRINTED: r.printed_area_m2,
                SOURCE_RASTER: r.raster_area_m2}[r.best_reference] or 0.0
    return {
        "rooms_with_a_vector_face": sum(
            1 for r in rooms if r.vector_area_m2 is not None),
        "rooms_compared": len(scored),
        "rooms_without_any_reference": sum(
            1 for r in rooms if r.best_reference == NOT_AVAILABLE),
        "rooms_compared_on_unlike_bases": sum(
            1 for r in scored if not r.bases_match),
        # §16 — the two kinds of row must never be averaged together, and the
        # approximate ones are not accuracy at all.
        "rooms_measured_from_a_polygon": sum(
            1 for r in scored if r.is_measured),
        "rooms_on_a_scalar_approximation": sum(
            1 for r in scored if not r.is_measured),
        "measured_median_abs_pct": _r(_percentile(
            [r.headline_abs_pct for r in scored if r.is_measured], 50), 2),
        "approximation_warning": (
            "rows whose conversion_kind is "
            f"{DIAGNOSTIC_APPROXIMATION} are NOT per-room accuracy. They are "
            "a scalar centreline-to-clear conversion with no corner term, "
            "kept only to compare against the measured polygon"),
        "median_abs_pct": _r(_percentile(pcts, 50), 2),
        "p90_abs_pct": _r(_percentile(pcts, 90), 2),
        "max_abs_pct": _r(max(pcts), 2) if pcts else None,
        "worst_room": (None if worst is None else {
            "space_id": worst.space_id,
            "abs_pct": _r(worst.headline_abs_pct, 2),
            "vector_area_m2": _r(worst.comparable_vector_area_m2),
            "reference": worst.best_reference}),
        "by_reference": {s: sum(1 for r in scored if r.best_reference == s)
                         for s in COMPARISON_SOURCES},
        "secondary_total_diagnostic": {
            "vector_total_m2": _r(vec, 2),
            "reference_total_m2": _r(ref, 2),
            "total_pct": _r(abs(vec - ref) / ref * 100, 2) if ref else None,
            "why": ("SECONDARY. Over- and under-measurements cancel in a "
                    "total, so this figure can look excellent while "
                    "individual rooms are wrong. Read the distribution above "
                    "first")},
        "acceptance_threshold": None,
        "acceptance_note": ("no production acceptance threshold is defined "
                            "from one project. A threshold chosen from this "
                            "run would be a number chosen to pass"),
    }
