"""E53 — per-room accuracy, reported as a distribution and never as one number.

The first instinct is to print

    total vector area   412.6 m2
    total site area     409.1 m2
    difference          0.9%

and it is worthless. A room measured 2 m2 too big and a room measured 2 m2 too
small cancel exactly, and the project total says the engine is accurate when
two rooms are wrong. A total is a check that ERRORS DID NOT ACCUMULATE; it is
not evidence that any individual room is right.

So this module reports:

    every room, with its own absolute difference and percentage
    the median absolute percentage
    the 90th percentile absolute percentage
    the worst room, by name

and only then the total, labelled as the secondary diagnostic it is.

NO ACCEPTANCE THRESHOLD IS DEFINED HERE. One project is not a population, and
a threshold set from 23010's first real run would be a number chosen to pass.
First measure the distribution; decide what is acceptable afterwards, with
evidence.

THE REFERENCE ANSWERS ARE NOT INPUTS. Vector faces are generated by the wall
graph before this module is called, and nothing here feeds back. A comparison
that could adjust the thing it compares is not a measurement.
"""

from __future__ import annotations

from dataclasses import dataclass

# What a comparison was made against. Each is a different kind of truth and
# they do not substitute for each other.
SOURCE_RASTER = "RASTER_SEGMENTATION"
SOURCE_PRINTED = "PRINTED_DESIGN_DIMENSION"
SOURCE_SITE = "SITE_MEASURED_QIYAL"

COMPARISON_SOURCES = (SOURCE_RASTER, SOURCE_PRINTED, SOURCE_SITE)

NOT_AVAILABLE = "NOT_AVAILABLE"

# The two bases this comparison keeps running into. A planar face is measured
# on wall centrelines because that is where the graph's edges are; a raster
# region is the clear internal opening.
WALL_CENTRELINE = "WALL_CENTRELINE"
CLEAR_INTERNAL = "CLEAR_INTERNAL_FINISH_FACE"

# How a centreline area was brought onto the clear-internal basis. Stated, and
# approximate: exact for a rectilinear room of uniform thickness, and it is
# reported as an adjustment rather than folded silently into the area.
ADJ_HALF_THICKNESS = "MINUS_PERIMETER_X_MEAN_HALF_WALL_THICKNESS"


class AccuracyError(RuntimeError):
    """A comparison was asked for between two things that are not comparable."""


@dataclass(frozen=True)
class RoomAccuracy:
    """One room, one vector face, and every reference that exists for it."""

    space_id: str
    space_face_id: str
    measurement_basis: str
    vector_area_m2: float | None = None
    vector_perimeter_m: float | None = None
    raster_area_m2: float | None = None
    raster_perimeter_m: float | None = None
    printed_area_m2: float | None = None
    site_area_m2: float | None = None
    # NEVER COMPARE UNLIKE BASES. A planar face walks WALL CENTRELINES; a
    # raster region is the CLEAR INTERNAL opening between finished faces. They
    # differ by roughly half a wall thickness all the way round, and on a 5.5 m
    # bedroom that is about 10% of the area — which would be read as 10% error
    # by anyone who did not know the bases were different.
    vector_basis: str = WALL_CENTRELINE
    reference_basis: str = CLEAR_INTERNAL
    vector_area_basis_adjusted_m2: float | None = None
    basis_adjustment_m2: float | None = None
    basis_adjustment_method: str = ""
    why: str = ""

    @property
    def comparable_vector_area_m2(self) -> float | None:
        """The vector area on the REFERENCE's basis, when that is possible.

        Falls back to the raw centreline area, and `bases_match` says which
        happened, so a percentage is never read as accuracy when it is really
        a basis difference.
        """
        if self.vector_basis == self.reference_basis:
            return self.vector_area_m2
        return (self.vector_area_basis_adjusted_m2
                if self.vector_area_basis_adjusted_m2 is not None
                else self.vector_area_m2)

    @property
    def bases_match(self) -> bool:
        return (self.vector_basis == self.reference_basis
                or self.vector_area_basis_adjusted_m2 is not None)

    def _diff(self, other: float | None) -> tuple[float | None, float | None]:
        v = self.comparable_vector_area_m2
        if v is None or other is None or other == 0:
            return None, None
        d = v - other
        return abs(d), abs(d) / other * 100

    @property
    def vs_raster(self) -> tuple[float | None, float | None]:
        return self._diff(self.raster_area_m2)

    @property
    def vs_printed(self) -> tuple[float | None, float | None]:
        return self._diff(self.printed_area_m2)

    @property
    def vs_site(self) -> tuple[float | None, float | None]:
        return self._diff(self.site_area_m2)

    @property
    def best_reference(self) -> str:
        """The strongest reference actually present, by source hierarchy."""
        if self.site_area_m2 is not None:
            return SOURCE_SITE
        if self.printed_area_m2 is not None:
            return SOURCE_PRINTED
        if self.raster_area_m2 is not None:
            return SOURCE_RASTER
        return NOT_AVAILABLE

    @property
    def headline_abs_pct(self) -> float | None:
        """The percentage against the strongest reference present."""
        return {SOURCE_SITE: self.vs_site, SOURCE_PRINTED: self.vs_printed,
                SOURCE_RASTER: self.vs_raster}.get(
                    self.best_reference, (None, None))[1]

    def record(self) -> dict:
        ra, rp = self.vs_raster
        pa, pp = self.vs_printed
        sa, sp = self.vs_site
        return {
            "space_id": self.space_id, "space_face_id": self.space_face_id,
            "measurement_basis": self.measurement_basis,
            "vector_area_m2": _r(self.vector_area_m2),
            "vector_perimeter_m": _r(self.vector_perimeter_m),
            "vector_basis": self.vector_basis,
            "reference_basis": self.reference_basis,
            "bases_match": self.bases_match,
            "vector_area_basis_adjusted_m2": _r(
                self.vector_area_basis_adjusted_m2),
            "basis_adjustment_m2": _r(self.basis_adjustment_m2),
            "basis_adjustment_method": self.basis_adjustment_method,
            "comparable_vector_area_m2": _r(self.comparable_vector_area_m2),
            "raster_area_m2": _r(self.raster_area_m2),
            "raster_perimeter_m": _r(self.raster_perimeter_m),
            "printed_area_m2": _r(self.printed_area_m2),
            "site_area_m2": _r(self.site_area_m2),
            "abs_diff_vs_raster_m2": _r(ra), "pct_vs_raster": _r(rp),
            "abs_diff_vs_printed_m2": _r(pa), "pct_vs_printed": _r(pp),
            "abs_diff_vs_site_m2": _r(sa), "pct_vs_site": _r(sp),
            "best_reference": self.best_reference,
            "headline_abs_pct": _r(self.headline_abs_pct),
            "why": self.why}


def _r(v, n: int = 3):
    return None if v is None else round(v, n)


def _percentile(values, q: float) -> float | None:
    """Nearest-rank percentile. Small samples, so no interpolation is honest."""
    if not values:
        return None
    xs = sorted(values)
    i = min(len(xs) - 1, max(0, int(round(q / 100 * len(xs) + 0.5)) - 1))
    return xs[i]


def distribution(rooms) -> dict:
    """The shape of the error across rooms — never one project percentage.

    The total appears last and says what it is: a check that errors did not
    accumulate, not a measure of per-room accuracy.
    """
    scored = [r for r in rooms if r.headline_abs_pct is not None]
    pcts = [r.headline_abs_pct for r in scored]
    worst = max(scored, key=lambda r: r.headline_abs_pct, default=None)
    vec = sum(r.comparable_vector_area_m2 or 0.0 for r in scored)
    ref = 0.0
    for r in scored:
        ref += {SOURCE_SITE: r.site_area_m2, SOURCE_PRINTED: r.printed_area_m2,
                SOURCE_RASTER: r.raster_area_m2}[r.best_reference] or 0.0
    return {
        "rooms_with_a_vector_face": sum(
            1 for r in rooms if r.vector_area_m2 is not None),
        "rooms_compared": len(scored),
        "rooms_without_any_reference": sum(
            1 for r in rooms if r.best_reference == NOT_AVAILABLE),
        "rooms_compared_on_unlike_bases": sum(
            1 for r in scored if not r.bases_match),
        "median_abs_pct": _r(_percentile(pcts, 50), 2),
        "p90_abs_pct": _r(_percentile(pcts, 90), 2),
        "max_abs_pct": _r(max(pcts), 2) if pcts else None,
        "worst_room": (None if worst is None else {
            "space_id": worst.space_id,
            "abs_pct": _r(worst.headline_abs_pct, 2),
            "vector_area_m2": _r(worst.comparable_vector_area_m2),
            "reference": worst.best_reference}),
        "by_reference": {s: sum(1 for r in scored if r.best_reference == s)
                         for s in COMPARISON_SOURCES},
        "secondary_total_diagnostic": {
            "vector_total_m2": _r(vec, 2),
            "reference_total_m2": _r(ref, 2),
            "total_pct": _r(abs(vec - ref) / ref * 100, 2) if ref else None,
            "why": ("SECONDARY. Over- and under-measurements cancel in a "
                    "total, so this figure can look excellent while "
                    "individual rooms are wrong. Read the distribution above "
                    "first")},
        "acceptance_threshold": None,
        "acceptance_note": ("no production acceptance threshold is defined "
                            "from one project. A threshold chosen from this "
                            "run would be a number chosen to pass"),
    }
